site_name: TJGM
site_description: The best place for technical GTA guides, news, videos and more.
site_url: https://tjgm.dev/

nav:
  - Home: index.md

  - News:
    - Index: news/index.md
    - Tags: news/tags.md

  - Mods:
    - Improved 2DFX: mods/Improved-2DFX/index.md
    - Improved Hyman Memorial Stadium 2DFX: mods/Improved-Hyman-Memorial-Stadium-2DFX/index.md
    - Pyramid 2DFX Fix: mods/Pyramid-2DFX-Fix/index.md
    - No Extra Air Resistance: mods/No-Extra-Air-Resistance/index.md
    - Weapon Coronas: mods/Weapon-Coronas/index.md
    - Orange Bulb Lampposts: mods/Orange-Bulb-Lampposts/index.md
    - Jizzy's Pleasure Dome Remastered 2DFX: mods/Jizzy's-Pleasure-Dome-Remastered-2DFX/index.md
    
  - Guides:

    - Grand Theft Auto IV:
      - Fixing GTA IV with 4 Mods: guides/gtaiv/Fixing-GTA-IV-with-4-Mods/index.md
      - Fixing GTA IV with 4 Mods on Steam Deck: guides/gtaiv/Fixing-GTA-IV-with-4-Mods-on-Steam-Deck/index.md
      - Fusion Overloader Tutorial: guides/gtaiv/Fusion-Overloader-Tutorial/index.md
      - Removing Rockstar Games Launcher from GTA IV: guides/gtaiv/Removing-Rockstar-Games-Launcher-from-GTA-IV/index.md

    - Grand Theft Auto San Andreas:
      - How to Downgrade EVERY Version of GTA San Andreas: guides/gtasa/How-to-Downgrade-EVERY-Version-of-GTA-San-Andreas/index.md

    - Grand Theft Auto Vice City:
      - How to Downgrade EVERY Version of GTA Vice City: guides/gtavc/How-to-Downgrade-EVERY-Version-of-GTA-Vice-City/index.md

    - Grand Theft Auto III:
        - How to Downgrade EVERY Version of GTA III: guides/gtaiii/How-to-Downgrade-EVERY-Version-of-GTA-III/index.md

  - Resources:

    - Grand Theft Auto IV:
      - Console Visuals Wiki: resources/gtaiv/Console-Visuals-Wiki/index.md
      - Fusion Fix Wiki:
        - Index: resources/gtaiv/Fusion-Fix-Wiki/index.md
        - Configuration File: resources/gtaiv/Fusion-Fix-Wiki/config.md
        - Download & Installation: resources/gtaiv/Fusion-Fix-Wiki/download.md
        - Fixes & Improvements: resources/gtaiv/Fusion-Fix-Wiki/fixes.md
        - In-Game Options: resources/gtaiv/Fusion-Fix-Wiki/options.md
        - New Cheats: resources/gtaiv/Fusion-Fix-Wiki/cheats.md
      - TJGM's Drag n' Drop Archive for GTA IV: resources/gtaiv/TJGM's-Drag-n'-Drop-Archive/index.md
      - ⭐ TJGM's GTA IV Mod List: https://www.patreon.com/TJGM/posts/tjgms-gta-iv-mod-164039827

    - Grand Theft Auto San Andreas:
      - ⭐ TJGM's San Andreas Mod List: https://www.patreon.com/TJGM/posts/tjgms-san-mod-162918692

    - Grand Theft Auto Vice City:
      - ⭐ TJGM's Vice City Mod List: https://www.patreon.com/TJGM/posts/tjgms-vice-city-162921129

theme:
  name: material
  custom_dir: overrides
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.webp
  favicon: assets/favicon.ico

  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Enable light mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Enable dark mode
      primary: black
      accent: deep purple

  features:
  - navigation.top
  - search.highlight
  - search.suggest
  - search.share
  - content.code.annotate
  - toc.follow

plugins:
  - search
  - meta
  - social:
      cards_layout: default/only/image
      cards_layout_options:
        background_color: "#00000000"
        background_image: docs/assets/hero.webp
  - blog:
      blog_dir: news
      archive_date_format: yyyy
      archive_url_date_format: yyyy
      post_url_format: "{slug}"
      categories_allowed:
        - Announcements
        - Mod Releases
        - Mod Updates
        - Roundups
        - News

  - tags:
      tags_allowed:
        - GTA VI
        - GTA V
        - GTA IV
        - GTA Vice City Stories
        - GTA Liberty City Stories
        - GTA San Andreas
        - GTA Vice City
        - GTA III
        - GTA II
        - GTA


markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "#"


extra:
  analytics:
    provider: google
    property: G-KD191PFY0H
  consent:
    title: Cookie consent
    description: >- 
      We use cookies for Google Analytics, this allows us to track site usage and visits. You can disable cookies if you wish.
  social:
    - icon: fontawesome/brands/patreon
      link: https://www.patreon.com/TJGM
      name: Patreon

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_tjgm_
      name: Instagram

    - icon: fontawesome/brands/twitch
      link: https://twitch.tv/tjgm
      name: Twitch

    - icon: fontawesome/brands/x-twitter
      link: https://x.com/TJGM_
      name: X

    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TJGM
      name: YouTube

extra_css:
  - stylesheets/compare-slider.css
  - stylesheets/maincolours.css
  - stylesheets/share.css
  - stylesheets/home.css
  - stylesheets/hero.css

  
extra_javascript:
  - js/compare-slider.js
  - js/parallax.js
  - js/share.js

validation:
  nav:
    omitted_files: ignore

copyright: >
  Copyright © 2026 TJGM. <a href="#__consent"><u>Cookie settings</u></a>